version: '3'

tasks:
  build:app:  
    cmds:
      - cd ./build &&  rm -rf .shake && cabal build
    aliases: 
      - ba
    silent: true 

  build:site:
    cmds: 
      - rm -rf docs && cd ./build && cabal run 
    aliases:
      - bs
    silent: true 
  deploy:site:
    cmds:
      - cp ./build/docs ./dist
      - git push origin :gh-pages && git subtree push --prefix dist origin gh-pages" 
    aliases:
      - ds
    silent: true